# Docker Compose configuration for Zephyr Telemetry Infrastructure
# This sets up Grafana Alloy for collecting and forwarding OpenTelemetry data

services:
  # Grafana Alloy service for telemetry collection and processing
  grafana-alloy:
    image: grafana/alloy:latest
    container_name: grafana-alloy
    # Mount the telemetry configuration file
    volumes:
      - ./config.alloy:/etc/alloy/config.alloy
    # Expose ports for telemetry data collection and management
    ports:
      - '12345:12345' # Alloy HTTP UI/API (if enabled)
      - '4317:4317' # OTLP gRPC - for receiving telemetry data
      - '4318:4318' # OTLP HTTP - for receiving telemetry data
    # Load environment variables from .env file
    env_file:
      - .env
    # Command to run Alloy with the configuration
    command:
      [
        'run',
        '--server.http.listen-addr=0.0.0.0:12345',
        '/etc/alloy/config.alloy',
      ]
    # Restart policy for reliability
    restart: always
