name: Setup Node and PNPM
description: Sets up Node.js and PNPM with caching

inputs:
  os:
    required: true
    description: 'Operating system'
    default: ubuntu-latest
  node-version:
    required: true
    description: 'Node.js version'
    default: '24'

runs:
  using: 'composite'
  steps:
    - uses: pnpm/action-setup@v4
      with:
        run_install: false
    - uses: actions/setup-node@v6
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'
        cache-dependency-path: '**/pnpm-lock.yaml'
        registry-url: 'https://registry.npmjs.org'
    - run: pnpm install --prefer-offline
      shell: bash
