name: Setup Node and PNPM
description: Sets up Node.js and PNPM with caching

inputs:
  os:
    required: true
    description: 'Operating system'
    default: ubuntu-latest
  node-version:
    required: true
    description: 'Node.js version'
    default: 21

runs:
  using: 'composite'
  steps:
    - uses: pnpm/action-setup@v2
      with:
        version: 9
        run_install: false
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'
        cache-dependency-path: '**/pnpm-lock.yaml'
    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
    - uses: actions/cache@v3
      name: Cache pnpm store
      with:
        path: |
          ${{ env.STORE_PATH }}
          node_modules/.cache
          ~/.cache/Cypress
          .nx/cache
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**/package.json') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}-
          ${{ runner.os }}-pnpm-store-
    - name: Install dependencies
      shell: bash
      run: |
        pnpm config set store-dir ${{ env.STORE_PATH }}
        pnpm install --prefer-offline --frozen-lockfile
