packages:
  - 'libs/*'
  - 'examples/*'
  - 'examples/vite-react-mf/*'
  - 'examples/rspack-mf/*'
  - 'examples/modern-js/*'
  - 'examples/modern-js-mf/*'
  # - 'examples/modern-js-ssr/*'

installOptions:
  preferOnline: false
  frozenLockfile: true
