packages:
  - libs/**
  - packages/**
  - examples/**
  - e2e/**
  - '!**/dist/**'

catalogs:
  babel:
    '@babel/core': ^7.26.10
    '@babel/preset-react': ^7.26.3
    '@babel/runtime': ^7.26.10
  esbuild:
    esbuild: ^0.27.0
  modernjs:
    '@modern-js/app-tools': ^3.5.0
    '@modern-js/plugin-ssg': ^3.5.0
    '@modern-js/runtime': ^3.5.0
    '@modern-js/tsconfig': ^3.5.0
  module-federation:
    '@module-federation/automatic-vendor-federation': ^1.2.1
    '@module-federation/enhanced': ^2.6.0
    '@module-federation/runtime': ^2.2.3
    '@module-federation/vite': ^1.13.2
  parcel:
    '@parcel/config-default': ^2.16.4
    '@parcel/core': ^2.16.4
    '@parcel/plugin': ^2.16.4
    '@parcel/types': ^2.16.4
    parcel: ^2.16.4
  plugin-shared:
    is-ci: ^4.1.0
  postcss:
    postcss: ^8.5.10
    postcss-loader: ^8.0.0
  react:
    '@jest/globals': ^29.7.0
    '@testing-library/react': ^16.2.0
  react18:
    '@types/react': 18.3.28
    '@types/react-dom': 18.3.7
    react: 18.3.1
    react-dom: 18.3.1
    react-refresh: ^0.18.0
  react19:
    '@types/react': ^19.0.12
    '@types/react-dom': ~19.2.0
    react: ^19.2.6
    react-dom: ^19.2.6
  rolldown:
    rolldown: 1.0.0-rc.6
  rollup4:
    '@rollup/plugin-url': 8.0.2
    '@svgr/rollup': 8.1.0
    rollup: ^4.36.0
  rspack:
    '@rsbuild/core': ^2.1.2
    '@rsbuild/plugin-react': ^2.1.0
    '@rspack/cli': ^2.1.2
    '@rspack/core': ^2.1.2
    '@rspack/plugin-react-refresh': ^2.0.2
  rslib:
    '@rslib/core': ^0.23.1
  rspress:
    '@rspress/core': ^2.0.0-rc.1
  rstest:
    '@rstest/core': ^0.10.6
  swc:
    '@swc-node/register': 1.11.1
    '@swc/cli': 0.8.0
    '@swc/core': 1.15.8
    '@swc/helpers': 0.5.19
    '@swc/jest': 0.2.39
    swc-loader: ^0.2.6
  tailwind:
    tailwindcss: ^3.4.11
  typescript:
    '@types/is-ci': 3.0.4
    '@types/jest': 29.5.14
    '@types/node': 22.19.13
    '@types/node-persist': ^3.1.8
    '@types/yargs': ^17.0.33
    ts-jest: ^29.2.6
    tslib: ^2.8.1
    typescript: ~5.9.0
  vite7:
    '@vitejs/plugin-react': ^4.3.4
    '@vitejs/plugin-react-swc': ^3.8.1
    autoprefixer: ^10.1.0
    globals: ^15.9.0
    postcss: ^8.5.10
    postcss-loader: ^8.0.0
    vite: ^7.3.5
  vitest:
    '@vitest/coverage-v8': ^3.0.9
    '@vitest/ui': ^3.0.9
    vitest: ^3.0.9
  webpack5:
    '@svgr/webpack': ^8.1.0
    webpack: ^5.103.0

onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@parcel/watcher'
  - '@swc/core'
  - core-js
  - core-js-pure
  - esbuild
  - lmdb
  - msgpackr-extract
  - msw
  - sharp
  - workerd
