name: Import secrets and variables to Depot CI
on: push

permissions:
  id-token: write
  contents: read

jobs:
  secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: depot/setup-action@v1
      - name: Import secrets
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          CODSPEED_TOKEN: ${{ secrets.CODSPEED_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
          ZEPHYR_AUTH_TOKEN: ${{ secrets.ZEPHYR_AUTH_TOKEN }}
          ZE_CI_TOKEN: ${{ secrets.ZE_CI_TOKEN }}
          ZE_SECRET_TOKEN: ${{ secrets.ZE_SECRET_TOKEN }}
          ZE_WORKFLOW_AUTOMATION_APP_ID: ${{ secrets.ZE_WORKFLOW_AUTOMATION_APP_ID }}
          ZE_WORKFLOW_AUTOMATION_PRIVATE_KEY: ${{ secrets.ZE_WORKFLOW_AUTOMATION_PRIVATE_KEY }}
        run: |
          unset DEPOT_TOKEN
          depot ci secrets add ANTHROPIC_API_KEY="$ANTHROPIC_API_KEY" CODSPEED_TOKEN="$CODSPEED_TOKEN" GH_TOKEN="$GH_TOKEN" TURBO_TOKEN="$TURBO_TOKEN" ZEPHYR_AUTH_TOKEN="$ZEPHYR_AUTH_TOKEN" ZE_CI_TOKEN="$ZE_CI_TOKEN" ZE_SECRET_TOKEN="$ZE_SECRET_TOKEN" ZE_WORKFLOW_AUTOMATION_APP_ID="$ZE_WORKFLOW_AUTOMATION_APP_ID" ZE_WORKFLOW_AUTOMATION_PRIVATE_KEY="$ZE_WORKFLOW_AUTOMATION_PRIVATE_KEY" --repo ZephyrCloudIO/zephyr-packages
  variables:
    runs-on: ubuntu-latest
    steps:
      - uses: depot/setup-action@v1
      - name: Import variables
        env:
          ZE_API_DEV: ${{ vars.ZE_API_DEV }}
          ZE_API_GATE_DEV: ${{ vars.ZE_API_GATE_DEV }}
          DO_NOT_TRACK: ${{ vars.DO_NOT_TRACK }}
          TURBO_TELEMETRY_DISABLED: ${{ vars.TURBO_TELEMETRY_DISABLED }}
        run: |
          unset DEPOT_TOKEN
          depot ci vars add ZE_API_DEV="$ZE_API_DEV" ZE_API_GATE_DEV="$ZE_API_GATE_DEV" DO_NOT_TRACK="$DO_NOT_TRACK" TURBO_TELEMETRY_DISABLED="$TURBO_TELEMETRY_DISABLED" --repo ZephyrCloudIO/zephyr-packages
