# This workflow has been replaced by publish_packages.yml
# Redirect users to use the unified workflow

name: On Canary Release (Deprecated)
on:
  workflow_dispatch:

jobs:
  redirect:
    runs-on: ubuntu-latest
    steps:
      - name: Redirect to unified workflow
        run: |
          echo "⚠️ This workflow is deprecated!"
          echo "Please use the 'Publish Packages' workflow instead."
          echo "Go to Actions -> Publish Packages -> Run workflow -> Select 'canary'"
          exit 1
