name: On Canary Release
on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          os: ubuntu-latest
          node-version: 20
      - name: Build packages
        run: pnpm dlx nx run-many -t build --projects="libs/*"
      - name: Patch versions
        run: |
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          pnpm ze-version-patch 0.0.0-canary-$TIMESTAMP
      - name: Publish package on NPM 📦
        run: pnpm ze-publish --tag=canary
