name: On Pre-release
on:
  release:
    types: [prereleased]

permissions:
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Build packages
        run: pnpm build
      - name: Publish package on NPM 📦
        run: pnpm ze-publish --tag=next
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
