name: On Pre-release
on:
  release:
    types: [prereleased]

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          os: ubuntu-latest
          node-version: 20
      - name: Build packages
        run: pnpm dlx nx run-many -t build --projects="libs/*"
      - name: Publish package on NPM 📦
        run: pnpm ze-publish --tag=next
