name: On Release
on:
  release:
    types: [released]

jobs:
  setup:
    uses: ./.github/workflows/setup.yml
    with:
      os: ubuntu-latest
      node-version: 20

  publish:
    needs: setup
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js and PNPM
        uses: ./.github/workflows/setup.yml
        with:
          os: ubuntu-latest
          node-version: 20
      - name: Build packages
        run: pnpm dlx nx run-many -t build --projects="libs/*"
      - name: Release libraries
        run: pnpm dlx nx run-many -t release --projects="libs/*"
