name: On Release
on:
  release:
    types: [released]

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Release libraries (promote tags from next to latest)
        run: pnpm nx run-many -t release --projects="libs/*"
