name: Test Zephyr Examples

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  # Allow manual runs
  workflow_dispatch:

jobs:
  test-examples:
    name: Test Examples
    runs-on: ubuntu-latest
    env:
      ZEPHYR_AUTH_TOKEN: ${{ secrets.ZEPHYR_AUTH_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21'

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9.9.0

      - name: Install Dependencies
        run: |
          pnpm install

      - name: Build Libraries
        run: |
          pnpm run build

      - name: Install Packages in Examples
        run: |
          # Install dependencies in each example project using workspace references
          find examples -name "package.json" -not -path "**/node_modules/*" -exec sh -c 'cd $(dirname {}) && echo "Installing dependencies in $(pwd)" && pnpm install --prefer-workspace-packages' \;

      - name: Run Testing Matrix
        run: |
          pnpm run test:examples
